import { expect, test } from "@playwright/test";

// Contract tests against a real wrangler dev (research.md's testing rationale,
// specs/002-error-monitoring) — hand-crafted envelope bodies matching contracts/ingest-api.md's
// grammar exactly, rather than requiring a full SDK install in the test harness. The demo
// project's DSN key is read from the local D1 database at test setup time rather than hardcoded,
// so this doesn't silently drift from whatever the baseline migration actually seeds.

const DEMO_PROJECT_ID = "demo";

function buildEnvelope(eventId: string, payload: Record<string, unknown>): string {
  const eventJson = JSON.stringify({ event_id: eventId, ...payload });
  const payloadBytes = new TextEncoder().encode(eventJson).length;
  const envelopeHeader = JSON.stringify({ event_id: eventId });
  const itemHeader = JSON.stringify({ type: "event", length: payloadBytes });
  return [envelopeHeader, itemHeader, eventJson].join("\n");
}

function jsShapedPayload(): Record<string, unknown> {
  return {
    platform: "javascript",
    level: "error",
    exception: {
      values: [{
        type: "TypeError",
        value: "Cannot read properties of undefined",
        stacktrace: {
          frames: [
            { filename: "vendor.min.js", function: "n", lineno: 1, colno: 42, in_app: false },
            { filename: "app.min.js", function: "useCheckout", lineno: 3, colno: 15, in_app: true },
          ],
        },
      }],
    },
  };
}

function pythonShapedPayload(): Record<string, unknown> {
  return {
    platform: "python",
    level: "error",
    exception: {
      values: [{
        type: "OperationalError",
        value: "too many connections",
        stacktrace: {
          frames: [
            {
              filename: "db/pool.py",
              function: "acquire",
              module: "db.pool",
              lineno: 42,
              in_app: true,
              vars: { retries: "3" },
            },
          ],
        },
      }],
    },
  };
}

// The DSN key isn't known at module-eval time (it's per-environment, generated by the migration),
// so it's looked up straight out of the local preview D1 instance rather than hardcoded. No public
// endpoint exposes this (by design — it's only ever surfaced inside the authenticated app shell).
// Contract tests run against a local-only wrangler dev whose D1 state this suite controls, so
// reading it directly out of band is acceptable here. Memoized since every test needs it and the
// lookup shells out to wrangler.
let dsnKeyPromise: Promise<string> | null = null;

function getDsnKey(): Promise<string> {
  if (!dsnKeyPromise) dsnKeyPromise = lookupDsnKey();
  return dsnKeyPromise;
}

async function lookupDsnKey(): Promise<string> {
  const command = new Deno.Command(Deno.execPath(), {
    args: [
      "run",
      "-A",
      "npm:wrangler",
      "d1",
      "execute",
      "flightdeck-preview",
      "--local",
      "--env",
      "preview",
      "--command",
      "SELECT dsn_public_key FROM projects WHERE id='demo'",
      "--json",
    ],
    stdout: "piped",
    stderr: "piped",
  });
  const { success, stdout, stderr } = await command.output();
  if (!success) {
    throw new Error(`wrangler d1 execute failed: ${new TextDecoder().decode(stderr)}`);
  }

  const [{ results }] = JSON.parse(new TextDecoder().decode(stdout)) as [
    { results: [{ dsn_public_key: string }] },
  ];
  if (!results[0]?.dsn_public_key) {
    throw new Error("demo project has no dsn_public_key — has migration 0002 been applied?");
  }
  return results[0].dsn_public_key;
}

test("a JS-shaped event is accepted and produces an issue", async ({ request }) => {
  const dsnKey = await getDsnKey();
  const body = buildEnvelope(crypto.randomUUID(), jsShapedPayload());

  const response = await request.post(
    `/api/${DEMO_PROJECT_ID}/envelope?sentry_key=${dsnKey}&sentry_version=7`,
    { data: body },
  );
  expect(response.status()).toBe(200);
});

test("a Python-shaped event (header-based auth) is accepted", async ({ request }) => {
  const dsnKey = await getDsnKey();
  const body = buildEnvelope(crypto.randomUUID(), pythonShapedPayload());

  const response = await request.post(`/api/${DEMO_PROJECT_ID}/envelope`, {
    data: body,
    headers: {
      "X-Sentry-Auth":
        `Sentry sentry_version=7, sentry_client=sentry.python/1.0, sentry_key=${dsnKey}`,
    },
  });
  expect(response.status()).toBe(200);
});

test("an unknown DSN key is rejected, fail closed", async ({ request }) => {
  const body = buildEnvelope(crypto.randomUUID(), jsShapedPayload());
  const response = await request.post(
    `/api/${DEMO_PROJECT_ID}/envelope?sentry_key=not-a-real-key&sentry_version=7`,
    { data: body },
  );
  expect(response.status()).toBe(403);
});

test("submitting the same event twice does not duplicate it", async ({ request }) => {
  const dsnKey = await getDsnKey();
  const eventId = crypto.randomUUID();
  const body = buildEnvelope(eventId, jsShapedPayload());
  const url = `/api/${DEMO_PROJECT_ID}/envelope?sentry_key=${dsnKey}&sentry_version=7`;

  const first = await request.post(url, { data: body });
  expect(first.status()).toBe(200);
  const second = await request.post(url, { data: body });
  expect(second.status()).toBe(200); // still accepted, just a no-op — not an error
});

test("exceeding the rate limit responds 429 with the X-Sentry-Rate-Limits header", async ({ request }) => {
  const dsnKey = await getDsnKey();
  const url = `/api/${DEMO_PROJECT_ID}/envelope?sentry_key=${dsnKey}&sentry_version=7`;

  let last;
  for (let i = 0; i < 110; i++) {
    last = await request.post(url, {
      data: buildEnvelope(crypto.randomUUID(), { message: `spam ${i}` }),
    });
    if (last.status() === 429) break;
  }

  expect(last?.status()).toBe(429);
  const header = last?.headers()["x-sentry-rate-limits"];
  expect(header).toMatch(/^\d+::key$/);
});
